### ISSUE TITLE
[suggestion/request] auto-run the linker tool on existing notes

### ISSUE THREAD

**Issue by firinael** [perkinsben/obs_tools#15]
Hi, would it be possible to enable the Auto-Linker to automatically go through existing notes and link words that are already found in another note, or words specified?

For example, I have a note that's an index where I store every note that I'd consider something I might want to revisit to remind myself of a concept. Would it be possible for the Auto-Linker to go through other notes and link the words/aliases found in those, to the notes found in the index?

Sorry if my explanation was poor, I'm not a native speaker.

**Comment by perkinsben** [comment]
I don't think everything you're looking for is possible here, but you might be able to get halfway there. Remember, the tool only operates on clipboard text, it can't look in files and do linking there.

You could create an empty vault folder and place inside that an aliases file (aliases.yml). In this file, you would add the note titles from your index.

```
Oranges:
- Oranges

Apples:
- Apples

Bananas:
- Bananas
```
You have to duplicate each entry due to how the aliases function works.

By doing this, you're providing to the tool an alternative list of notes that you care about (instead of the file names or aliases gathered from metadata).

When running: python obs-linkr.py c:\path\to\empty\vault\folder -y
